# Generated by Django 3.2.3 on 2021-08-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateField(blank=True)),
                ('client', models.CharField(max_length=45)),
                ('batch', models.CharField(max_length=45)),
                ('volume', models.CharField(max_length=45)),
                ('basis', models.CharField(max_length=45)),
                ('ship_start', models.DateField(blank=True)),
                ('ship_end', models.DateField(blank=True)),
                ('vessel_name', models.CharField(max_length=45)),
                ('last_day_pricing', models.DateField(blank=True)),
                ('eta_gh', models.DateField(blank=True)),
                ('etd_gh', models.DateField(blank=True)),
                ('eta_disport', models.DateField(blank=True)),
                ('notes', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='shipmentTrackerApp.user')),
            ],
        ),
    ]
