# Generated by Django 3.2.3 on 2021-08-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipmentTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='shipmentTrackerApp.user'),
        ),
    ]
