# Generated by Django 3.2.3 on 2021-08-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipmentTrackerApp', '0003_auto_20210801_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ship',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
