# Generated by Django 3.2.3 on 2021-08-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipmentTrackerApp', '0005_auto_20210801_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='last_day_pricing',
            field=models.DateField(blank=True, null=True),
        ),
    ]
